apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::303062867354:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S5AYF6ACOAHO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::303062867354:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-18T16:56:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1516"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6ffd2f92-d411-43e7-b626-f24351e6e8dc
