apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::303062867354:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X0OQCNP7BQ6I
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: rolearn: arn:aws:iam::303062867354:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-17T17:50:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1528"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 62109631-8e5c-4ccf-9149-97db3a764642
