apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::303062867354:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4FV89V78H484
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::303062867354:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-18T15:01:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1689"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d6ad6eca-dabc-48cd-b0aa-4195a0a71cc1
